//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLinq_CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class deneyim
    {
        public int id { get; set; }
        public string deneyim1 { get; set; }
        public string aciklama { get; set; }
    }
}
