//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkLinq_CV
{
    using System;
    using System.Collections.Generic;
    
    public partial class hakkimda
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string adres { get; set; }
        public string tel { get; set; }
        public string eposta { get; set; }
        public string hakkimdaYazi { get; set; }
    }
}
